name: Weekly Gap Notifier

on:
  schedule:
    - cron: '0 15 * * 0'  # Tous les dimanches à 17h (heure de Paris = UTC+2 en été)
  workflow_dispatch:  # Permet d'exécuter manuellement

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Load .env file
        run: |
          if [ -f .env ]; then
            export $(cat .env | xargs)
          fi

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install requests python-dotenv

      - name: Run IG Gap Notifier
        run: python gap_notifier_ig.py
