name: Weekly Gap Notifier

on:
  schedule:
    - cron: '0 15 * * 0'  # Tous les dimanches à 17:00 (heure de Paris en été)
  workflow_dispatch:      # Lancement manuel

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # Charge le fichier .env dans l'environnement des étapes suivantes (robuste)
      - name: Load .env into env
        run: |
          if [ -f .env ]; then
            sed -e '/^\s*#/d' -e '/^\s*$/d' .env >> $GITHUB_ENV
          fi

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install requests python-dotenv pycryptodome

      - name: Run IG Gap Notifier
        run: python gap_notifier_ig.py
