name: Weekly Gap Notifier (FXCM)

on:
  schedule:
    - cron: '0 15 * * 0'   # Tous les dimanches à 17:00 (Paris, été)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Load .env file
        run: |
          if [ -f .env ]; then
            export $(grep -v '^#' .env | xargs)
          fi

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install fxcmpy python-dotenv pandas requests

      - name: Run FXCM Gap Notifier (dry-run)
        env:
          DRY_RUN: "1"
          OUTPUT_LOG: "gap_output.txt"
        run: python gap_notifier_fxcm.py

      - name: Upload log file
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gap-log
          path: gap_output.txt
          if-no-files-found: warn
