name: Weekly Gap Notifier (Discord ON)

on:
  schedule:
    # DIMANCHE 22:05 UTC (≈ 00:05 lundi Europe/Paris en été)
    - cron: '5 22 * * 0'
  # tu peux garder le déclenchement manuel, mais
  # ATTENTION: si tu lances avant 22:00 UTC le dimanche,
  # le script ne postera volontairement rien.
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Load .env into env
        shell: bash
        run: |
          set -euo pipefail
          if [ -f .env ]; then
            sed -e '/^\s*#/d' -e '/^\s*$/d' .env >> "$GITHUB_ENV"
          fi

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        shell: bash
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip
          python -m pip install yfinance pandas requests python-dotenv

      - name: Run Gap Notifier (Discord ON)
        shell: bash
        env:
          DRY_RUN: "0"            # 0 => envoi Discord activé
          OUTPUT_LOG: "gap_output.txt"
        run: |
          set -euo pipefail
          python gap_notifier_ig.py

      - name: Show result
        shell: bash
        run: |
          set -euo pipefail
          echo "----- gap_output.txt -----"
          if [ -f gap_output.txt ]; then
            cat gap_output.txt
          else
            echo "gap_output.txt introuvable"
          fi

      - name: Upload log file
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gap-log
          path: gap_output.txt
          if-no-files-found: warn
