name: Daily Gap Notifier (Discord ON)

on:
  schedule:
    # Été (UTC+2) : 15:10 UTC = 17:10 Paris
    - cron: '10 15 * * *'
    # Hiver (UTC+1) : 16:10 UTC = 17:10 Paris
    - cron: '10 16 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Load .env into env
        shell: bash
        run: |
          if [ -f .env ]; then
            sed -e '/^\s*#/d' -e '/^\s*$/d' .env >> $GITHUB_ENV
          fi

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install yfinance pandas requests python-dotenv

      - name: Run Gap Notifier (Discord ON)
        env:
          DRY_RUN: "0"
          OUTPUT_LOG: "gap_output.txt"
        run: python gap_notifier_ig.py

      - name: Show result
        shell: bash
        run: |
          echo "----- gap_output.txt -----"
          if [ -f gap_output.txt ]; then
            cat gap_output.txt
          else
            echo "gap_output.txt introuvable"
          fi

      - name: Upload log file
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gap-log
          path: gap_output.txt
          if-no-files-found: warn
